/* BestShopio Admin · Orders prototype — sample data.
   Shaped after reference/bestvoy-admin .../orders/type.ts (OrderRecord, OrderItem,
   OrderShippingInfo) and api/modules/admin/orders.ts (ApiOrderDetail).
   Money is in store currency (USD $). No real PII / secrets.

   Fulfillment status is DERIVED from order status in app.js (mirrors
   FulfillmentStatusCell.tsx: shipped/review/archived -> Fulfilled, refund -> '--',
   everything else -> Unfulfilled), so it is not stored on rows. */
(function () {
  // ---- Tabs (orders/type.ts ORDERS_TAB + ORDERS_TAB_OPTIONS) ----
  const TABS = [
    { key: 'all',     label: 'All' },
    { key: 'to_pay',  label: 'To Pay' },
    { key: 'to_ship', label: 'To Ship' },
    { key: 'shipped', label: 'Shipped' },
    { key: 'review',  label: 'Awaiting Review' },
    { key: 'archived',label: 'Archived' },
    { key: 'refund',  label: 'Refund' },
    { key: 'cancel',  label: 'Cancel' },
  ];

  // ---- Keyword-type select (ORDERS_KEYWORD_OPTIONS) ----
  const KEYWORD_OPTIONS = [
    { label: 'Order number',  value: 'order_sn' },
    { label: 'Receiver',      value: 'receiver' },
    { label: 'Email',         value: 'email' },
    { label: 'Phone',         value: 'phone' },
    { label: 'Country/Region',value: 'country' },
    { label: 'Product name',  value: 'store_name' },
    { label: 'Product SPU',   value: 'product_spu' },
    { label: 'Product SKU',   value: 'product_sku' },
    { label: 'Product barcode', value: 'bar_code_number' },
    { label: 'Product ID',    value: 'product_id' },
    { label: 'Variant ID',    value: 'unique' },
    { label: 'User',          value: 'nickname' },
  ];

  // ---- Time-type select (ORDERS_TIME_OPTIONS) ----
  const TIME_OPTIONS = [
    { label: 'Creation time',    value: 'create_date' },
    { label: 'Payment time',     value: 'pay_date' },
    { label: 'Fulfillment time', value: 'delivery_date' },
  ];

  // ---- List rows (OrderRecord / ApiOrderListItem-shaped, flattened for the table) ----
  // order_status drives the OrderStatusCell pill + derived fulfillment. order_type:
  // 0 = standard shipping order, 1/2 = pickup/verify order (drives Verify action).
  const ORDERS = [
    // --- Subscription / Bundle sample orders (Subscriptions + Bundles integration) ---
    // sub = recurring/initial order tied to a contract (list shows a compact "Subscription" tag; contract/cycle live in detail).
    // bundle = order containing a bundle (list shows "Bundle" tag; detail groups the bundle's SKUs).
    {
      order_id: 5046, order_sn: 'EN1038', create_time: '2026-06-20 09:18', order_type: 0,
      user: { nickname: 'Grace Lee', uid: 80612 },
      shipping: { name: 'Grace Lee', first_name: 'Grace', last_name: 'Lee',
        detail: '118 King Street', detail2: 'Suite 6', city: 'Seattle', province: 'WA', post_code: '98101',
        country: 'United States', phone_code: '1', phone: '206 555 0188', email: 'grace.lee@example.com' },
      total: 121.96, order_status: 'to_ship', payment_status: 'paid', payment_method: 'Airwallex Card',
      pay_time: '2026-06-20 09:19', delivery_time: null,
      source: 'BestCheckout', shopify_writeback_status: 'synced', shopify_order_id: '#SHP-89161', shopify_writeback_detail: 'Written back to Shopify with bundle and subscription snapshots for fulfillment.',
      sub: { id: 'SUB-20471', cycle: 1, next: '2026-08-20', deliveryLabel: 'Delivery every 2 months (-$13.99)' },
      bundle: { id: 'BND-07', name: 'Coffee Office Pack' },
    },
    {
      order_id: 5045, order_sn: 'EN1037', create_time: '2026-06-19 06:00', order_type: 0,
      user: { nickname: 'Liam Smith', uid: 80452 },
      shipping: { name: 'Liam Smith', first_name: 'Liam', last_name: 'Smith',
        detail: '9 Oak Ave', detail2: '', city: 'Denver', province: 'CO', post_code: '80202',
        country: 'United States', phone_code: '1', phone: '720 555 0133', email: 'liam.s@example.com' },
      total: 46.99, order_status: 'shipped', payment_status: 'paid', payment_method: 'PayPal',
      pay_time: '2026-06-19 06:00', delivery_time: '2026-06-20 11:00',
      sub: { id: 'SUB-20452', cycle: 3, next: '2026-07-19', deliveryLabel: 'Delivery every 1 month' },
    },
    {
      order_id: 5044, order_sn: 'EN1036', create_time: '2026-06-18 10:30', order_type: 0,
      user: { nickname: 'Mia Anderson', uid: 80460 },
      shipping: { name: 'Mia Anderson', first_name: 'Mia', last_name: 'Anderson',
        detail: '19 Willow Ct', detail2: '', city: 'San Diego', province: 'CA', post_code: '92101',
        country: 'United States', phone_code: '1', phone: '619 555 0177', email: 'mia.a@example.com' },
      total: 41.99, order_status: 'to_ship', payment_status: 'paid', payment_method: 'Stripe Card',
      pay_time: '2026-06-18 10:31', delivery_time: null,
      source: 'BestCheckout', shopify_writeback_status: 'pending', shopify_order_id: '', shopify_writeback_detail: 'Waiting for Shopify Admin API acceptance. Fulfillment is held until write-back succeeds.',
      sub: { id: 'SUB-20460', cycle: 1, next: '2026-06-23' },
    },
    {
      order_id: 5043, order_sn: 'EN1035', create_time: '2026-06-17 15:12', order_type: 0,
      user: { nickname: 'Jordan Park', uid: 80588 },
      shipping: { name: 'Jordan Park', first_name: 'Jordan', last_name: 'Park',
        detail: '300 Spear St', detail2: 'Apt 12', city: 'San Francisco', province: 'CA', post_code: '94105',
        country: 'United States', phone_code: '1', phone: '415 555 0150', email: 'jordan.park@example.com' },
      total: 49.30, order_status: 'shipped', payment_status: 'paid', payment_method: 'PayPal',
      pay_time: '2026-06-17 15:13', delivery_time: '2026-06-18 09:30',
      bundle: { id: 'BND-01', name: 'Focus Gum — Multipack' },
    },
    {
      order_id: 5042, order_sn: 'EN1033', create_time: '2026-06-04 14:22', order_type: 0,
      user: { nickname: 'Emma Whitfield', uid: 81245 },
      shipping: { name: 'Emma Whitfield', first_name: 'Emma', last_name: 'Whitfield',
        detail: '482 Lakeview Drive', detail2: 'Apt 5B', city: 'Chicago', province: 'IL', post_code: '60614',
        country: 'United States', phone_code: '1', phone: '312 555 0148', email: 'emma.whitfield@example.com' },
      total: 172.60, order_status: 'to_ship', payment_status: 'paid', payment_method: 'Stripe Card',
      pay_time: '2026-06-04 14:24', delivery_time: null,
      source: 'BestCheckout', shopify_writeback_status: 'synced', shopify_order_id: '#SHP-89142', shopify_writeback_detail: 'Written back to Shopify and ready for the installed fulfillment app.',
    },
    {
      order_id: 5041, order_sn: 'EN1032', create_time: '2026-06-04 11:08', order_type: 0,
      user: { nickname: 'Liam Sørensen', uid: 80910 },
      shipping: { name: 'Liam Sørensen', first_name: 'Liam', last_name: 'Sørensen',
        detail: '17 Harbour Street', detail2: '', city: 'Sydney', province: 'NSW', post_code: '2000',
        country: 'Australia', phone_code: '61', phone: '2 8123 4567', email: 'liam.sorensen@example.com' },
      total: 96.00, order_status: 'to_pay', payment_status: 'unpaid', payment_method: '--',
      pay_time: null, delivery_time: null,
    },
    {
      order_id: 5040, order_sn: 'EN1031', create_time: '2026-06-03 19:41', order_type: 0,
      user: { nickname: 'Olivia Martins', uid: 80877 },
      shipping: { name: 'Olivia Martins', first_name: 'Olivia', last_name: 'Martins',
        detail: '226 Peachtree Rd NE', detail2: 'Suite 12', city: 'Atlanta', province: 'GA', post_code: '30309',
        country: 'United States', phone_code: '1', phone: '404 555 7781', email: 'olivia.martins@example.com' },
      total: 232.80, order_status: 'shipped', payment_status: 'paid', payment_method: 'PayPal',
      pay_time: '2026-06-03 19:43', delivery_time: '2026-06-04 09:15',
      source: 'BestCheckout', shopify_writeback_status: 'failed', shopify_order_id: '', shopify_writeback_detail: 'Shopify rejected the write-back because shipping profile data is stale. Retry after fixing Connection.',
    },
    {
      order_id: 5039, order_sn: 'EN1030', create_time: '2026-06-03 08:55', order_type: 1,
      user: { nickname: 'Noah Thompson', uid: 80541 },
      shipping: { name: 'Noah Thompson', first_name: 'Noah', last_name: 'Thompson',
        detail: '900 Westheimer Rd', detail2: '', city: 'Houston', province: 'TX', post_code: '77006',
        country: 'United States', phone_code: '1', phone: '713 555 2290', email: 'noah.t@example.com' },
      total: 64.00, order_status: 'review', payment_status: 'paid', payment_method: 'Stripe ApplePay',
      pay_time: '2026-06-03 08:57', delivery_time: '2026-06-03 15:02',
    },
    {
      order_id: 5038, order_sn: 'EN1029', create_time: '2026-06-02 22:13', order_type: 0,
      user: { nickname: 'Ava Robinson', uid: 80233 },
      shipping: { name: 'Ava Robinson', first_name: 'Ava', last_name: 'Robinson',
        detail: '54 Collins Street', detail2: 'Level 8', city: 'Melbourne', province: 'VIC', post_code: '3000',
        country: 'Australia', phone_code: '61', phone: '3 9123 8800', email: 'ava.robinson@example.com' },
      total: 148.50, order_status: 'archived', payment_status: 'paid', payment_method: 'PayPal Card',
      pay_time: '2026-06-02 22:15', delivery_time: '2026-06-03 10:40',
    },
    {
      order_id: 5037, order_sn: 'EN1028', create_time: '2026-06-02 16:30', order_type: 0,
      user: { nickname: 'William Hughes', uid: 79980 },
      shipping: { name: 'William Hughes', first_name: 'William', last_name: 'Hughes',
        detail: '11 King Street West', detail2: '', city: 'Toronto', province: 'ON', post_code: 'M5H 1A1',
        country: 'Canada', phone_code: '1', phone: '416 555 0199', email: 'w.hughes@example.com' },
      total: 78.00, order_status: 'refund', payment_status: 'paid', payment_method: 'Stripe Card',
      pay_time: '2026-06-02 16:33', delivery_time: null,
    },
    {
      order_id: 5036, order_sn: 'EN1027', create_time: '2026-06-01 13:47', order_type: 0,
      user: { nickname: 'Sophia Khan', uid: 79644 },
      shipping: { name: 'Sophia Khan', first_name: 'Sophia', last_name: 'Khan',
        detail: '64 Baker Street', detail2: 'Flat 3', city: 'London', province: 'England', post_code: 'W1U 7DF',
        country: 'United Kingdom', phone_code: '44', phone: '20 7946 0123', email: 'sophia.khan@example.com' },
      total: 112.00, order_status: 'cancel', payment_status: 'unpaid', payment_method: '--',
      pay_time: null, delivery_time: null,
    },
    {
      order_id: 5035, order_sn: 'EN1026', create_time: '2026-06-01 09:02', order_type: 0,
      user: { nickname: 'James Becker', uid: 79412 },
      shipping: { name: 'James Becker', first_name: 'James', last_name: 'Becker',
        detail: 'Friedrichstraße 110', detail2: '', city: 'Berlin', province: 'Berlin', post_code: '10117',
        country: 'Germany', phone_code: '49', phone: '30 1234 5678', email: 'james.becker@example.com' },
      total: 205.20, order_status: 'to_ship', payment_status: 'paid', payment_method: 'Stripe Klarna',
      pay_time: '2026-06-01 09:05', delivery_time: null,
    },
    {
      order_id: 5034, order_sn: 'EN1025', create_time: '2026-05-31 20:18', order_type: 0,
      user: { nickname: 'Isabella Cruz', uid: 79100 },
      shipping: { name: 'Isabella Cruz', first_name: 'Isabella', last_name: 'Cruz',
        detail: '320 Ocean Drive', detail2: '', city: 'Miami', province: 'FL', post_code: '33139',
        country: 'United States', phone_code: '1', phone: '305 555 6612', email: 'isabella.cruz@example.com' },
      total: 54.00, order_status: 'shipped', payment_status: 'paid', payment_method: 'Stripe GooglePay',
      pay_time: '2026-05-31 20:20', delivery_time: '2026-06-01 11:30',
    },
    {
      order_id: 5033, order_sn: 'EN1024', create_time: '2026-05-31 12:44', order_type: 0,
      user: { nickname: 'Benjamin Foster', uid: 78844 },
      shipping: { name: 'Benjamin Foster', first_name: 'Benjamin', last_name: 'Foster',
        detail: '78 Queen Street', detail2: 'Unit 6', city: 'Auckland', province: 'Auckland', post_code: '1010',
        country: 'New Zealand', phone_code: '64', phone: '9 123 4567', email: 'ben.foster@example.com' },
      total: 167.40, order_status: 'review', payment_status: 'paid', payment_method: 'PayPal',
      pay_time: '2026-05-31 12:46', delivery_time: '2026-06-01 08:10',
    },
    {
      order_id: 5032, order_sn: 'EN1023', create_time: '2026-05-30 17:09', order_type: 0,
      user: { nickname: 'Mia Andersson', uid: 78510 },
      shipping: { name: 'Mia Andersson', first_name: 'Mia', last_name: 'Andersson',
        detail: 'Drottninggatan 45', detail2: '', city: 'Stockholm', province: 'Stockholm', post_code: '111 21',
        country: 'Sweden', phone_code: '46', phone: '8 123 456', email: 'mia.andersson@example.com' },
      total: 88.00, order_status: 'archived', payment_status: 'paid', payment_method: 'Stripe Card',
      pay_time: '2026-05-30 17:12', delivery_time: '2026-05-31 09:55',
    },
    {
      order_id: 5031, order_sn: 'EN1022', create_time: '2026-05-30 10:25', order_type: 0,
      user: { nickname: 'Lucas Meyer', uid: 78233 },
      shipping: { name: 'Lucas Meyer', first_name: 'Lucas', last_name: 'Meyer',
        detail: '12 Rue de Rivoli', detail2: '', city: 'Paris', province: 'Île-de-France', post_code: '75004',
        country: 'France', phone_code: '33', phone: '1 42 60 30 30', email: 'lucas.meyer@example.com' },
      total: 142.20, order_status: 'to_ship', payment_status: 'paid', payment_method: 'Airwallex Card',
      pay_time: '2026-05-30 10:28', delivery_time: null,
    },
    {
      order_id: 5030, order_sn: 'EN1021', create_time: '2026-05-29 21:50', order_type: 0,
      user: { nickname: 'Charlotte Reed', uid: 77990 },
      shipping: { name: 'Charlotte Reed', first_name: 'Charlotte', last_name: 'Reed',
        detail: '255 Market Street', detail2: 'Apt 14C', city: 'San Francisco', province: 'CA', post_code: '94105',
        country: 'United States', phone_code: '1', phone: '415 555 3320', email: 'charlotte.reed@example.com' },
      total: 312.00, order_status: 'shipped', payment_status: 'paid', payment_method: 'PayPal',
      pay_time: '2026-05-29 21:52', delivery_time: '2026-05-30 12:00',
    },
    {
      order_id: 5029, order_sn: 'EN1020', create_time: '2026-05-29 08:33', order_type: 0,
      user: { nickname: 'Henry Walsh', uid: 77641 },
      shipping: { name: 'Henry Walsh', first_name: 'Henry', last_name: 'Walsh',
        detail: '9 Eyre Square', detail2: '', city: 'Galway', province: 'Connacht', post_code: 'H91 X2K3',
        country: 'Ireland', phone_code: '353', phone: '91 123 456', email: 'henry.walsh@example.com' },
      total: 47.00, order_status: 'to_pay', payment_status: 'unpaid', payment_method: '--',
      pay_time: null, delivery_time: null,
    },
    {
      order_id: 5028, order_sn: 'EN1019', create_time: '2026-05-28 15:12', order_type: 0,
      user: { nickname: 'Amelia Novak', uid: 77302 },
      shipping: { name: 'Amelia Novak', first_name: 'Amelia', last_name: 'Novak',
        detail: 'Wenceslas Square 14', detail2: '', city: 'Prague', province: 'Prague', post_code: '110 00',
        country: 'Czechia', phone_code: '420', phone: '221 123 456', email: 'amelia.novak@example.com' },
      total: 129.00, order_status: 'refund', payment_status: 'paid', payment_method: 'Stripe Card',
      pay_time: '2026-05-28 15:15', delivery_time: null,
    },
  ];

  // ---- Full detail records (keyed by order_id), shaped after ApiOrderDetail ----
  // items[] is a flat product list (ProductsCard.tsx renders a flat ant List).
  // product_price = after-discount line price; line_total =
  // pre-discount line price (shown struck-through when discounts exist).
  const IMG = (bg, fg, t) =>
    'data:image/svg+xml;utf8,' + encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" width="44" height="44"><rect width="44" height="44" rx="6" fill="' + bg + '"/>' +
      '<text x="22" y="27" font-family="Inter,Arial" font-size="13" font-weight="600" fill="' + fg + '" text-anchor="middle">' + t + '</text></svg>');

  const DETAILS = {
    // Bundle subscription initial order — bundle components are sold under one subscription contract.
    5046: {
      order_id: 5046, order_sn: 'EN1038', status: 'to_ship', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-20 09:18', pay_time: '2026-06-20 09:19',
      source: 'BestCheckout', shopify_writeback_status: 'synced', shopify_order_id: '#SHP-89161', shopify_writeback_detail: 'Written back to Shopify with bundle and subscription snapshots for fulfillment.',
      payment_method: 'Airwallex Card', delivery_name: '', delivery_id: '',
      user: { nickname: 'Grace Lee', uid: 80612 },
      shipping: { first_name: 'Grace', last_name: 'Lee', detail: '118 King Street', detail2: 'Suite 6',
        city: 'Seattle', province: 'WA', post_code: '98101', country: 'United States',
        phone_code: '1', phone: '206 555 0188', email: 'grace.lee@example.com' },
      note: 'QA sample: bundle subscription, one-time bundle, normal subscription, discounted normal item, and standard normal item in one order. Preserve item-level bundle and subscription snapshots for future renewals.',
      sub: { id: 'SUB-20471', cycle: 1, next: '2026-08-20', deliveryLabel: 'Delivery every 2 months (-$13.99)' },
      bundle: { id: 'BND-07', name: 'Coffee Office Pack' },
      total_num: 8, subtotal: 126.96, shipping_fee: 8.99, total: 121.96, paid_amount: 121.96,
      order_discounts: [{ name: 'WELCOME10', amount: 5.00 }],
      shipping_discounts: [{ name: 'FREESHIP', amount: 8.99 }],
      total_savings: 48.56,
      items: [
        { title: 'Signature Blend Coffee 500g', sku: 'Whole bean, 2 Pack', image: IMG('#f3ece1', '#7a5c3a', 'C'),
          unit_price: 34.99, qty: 2, line_total: 69.97, product_price: 48.00,
          discounts: [{ name: 'Bundle discount', amount: 7.98 }, { name: 'Delivery every 2 months', amount: 13.99 }],
          bundle: 'Coffee Office Pack', subLine: true,
          subscription: { id: 'SUB-20471', cycle: 1, next: '2026-08-20', deliveryLabel: 'Delivery every 2 months (-$13.99)' },
          bundleMeta: { bundleDiscount: 'Bundle discount (-$7.98)', subscriptionLabel: 'Delivery every 2 months (-$13.99)' } },
        { title: 'Coffee Brew Guide', sku: 'Digital download', image: IMG('#eef4ff', '#1d4ed8', 'G'),
          unit_price: 0, qty: 1, line_total: 0, product_price: 0, discounts: [],
          bundle: 'Coffee Office Pack', gift: true,
          bundleMeta: { bundleDiscount: 'Bundle discount (-$7.98)', subscriptionLabel: 'Delivery every 2 months (-$13.99)' } },
        { title: 'Ceramic Pour-Over Mug', sku: 'Stone / 12oz', image: IMG('#eef0f4', '#525a6b', 'M'),
          unit_price: 17.99, qty: 1, line_total: 17.99, product_price: 15.99,
          discounts: [{ name: 'MUG10', amount: 2.00 }] },
        { title: 'Reusable Coffee Filter', sku: 'Stainless steel / 2-cup', image: IMG('#eff8f3', '#18794e', 'F'),
          unit_price: 12.99, qty: 1, line_total: 12.99, product_price: 10.99, discounts: [],
          bundle: 'Home Barista Essentials', bundleMeta: { bundleDiscount: 'Bundle discount (-$8.00)' } },
        { title: 'Borosilicate Glass Carafe', sku: '600ml', image: IMG('#eef4ff', '#1d4ed8', 'B'),
          unit_price: 24.99, qty: 1, line_total: 24.99, product_price: 18.99, discounts: [],
          bundle: 'Home Barista Essentials', bundleMeta: { bundleDiscount: 'Bundle discount (-$8.00)' } },
        { title: 'Signature Blend Coffee 500g', sku: 'Whole bean', image: IMG('#f3ece1', '#7a5c3a', 'C'),
          unit_price: 26.60, qty: 1, line_total: 26.60, product_price: 24.00,
          discounts: [{ name: 'Delivery every 1 month', amount: 2.60 }], subLine: true,
          subscription: { id: 'SUB-20472', cycle: 1, next: '2026-07-20', deliveryLabel: 'Delivery every 1 month (-$2.60)' } },
        { title: 'Stainless Steel Coffee Scoop', sku: '30ml', image: IMG('#f5f2ed', '#8b6b43', 'S'),
          unit_price: 8.99, qty: 1, line_total: 8.99, product_price: 8.99, discounts: [] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-20 09:18' },
        { label: 'Captured by BestCheckout funnel', time: '2026-06-20 09:18' },
        { label: 'Payment captured · Airwallex Card', time: '2026-06-20 09:19' },
        { label: 'Subscription SUB-20471 started (Coffee Office Pack)', time: '2026-06-20 09:19' },
        { label: 'Subscription SUB-20472 started (Signature Blend Coffee)', time: '2026-06-20 09:19' },
        { label: 'One-time mug, Home Barista Essentials bundle, and coffee scoop included', time: '2026-06-20 09:19' },
        { label: 'Shopify write-back synced · #SHP-89161', time: '2026-06-20 09:19' },
      ],
    },
    // Subscription renewal order (cycle 3 of contract SUB-20452) with a one-time add-on.
    5045: {
      order_id: 5045, order_sn: 'EN1037', status: 'shipped', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-19 06:00', pay_time: '2026-06-19 06:00',
      payment_method: 'PayPal', delivery_name: 'USPS', delivery_id: 'US9341005512',
      user: { nickname: 'Liam Smith', uid: 80452 },
      shipping: { first_name: 'Liam', last_name: 'Smith', detail: '9 Oak Ave', detail2: '',
        city: 'Denver', province: 'CO', post_code: '80202', country: 'United States',
        phone_code: '1', phone: '720 555 0133', email: 'liam.s@example.com' },
      note: 'Subscription renewal with a one-time Vitamin D3 add-on.',
      sub: { id: 'SUB-20452', cycle: 3, next: '2026-07-19', deliveryLabel: 'Delivery every 1 month' },
      total_num: 2, subtotal: 46.99, shipping_fee: 0.00, total: 46.99, paid_amount: 46.99,
      order_discounts: [], shipping_discounts: [], total_savings: 0,
      items: [
        { title: 'Daily Multivitamin (60 ct)', sku: '60 ct', image: IMG('#eafaf0', '#1f8f4e', 'V'),
          unit_price: 32.00, qty: 1, line_total: 32.00, product_price: 32.00, discounts: [],
          subLine: true },
        { title: 'Vitamin D3 + K2 Softgels', sku: '90 ct', image: IMG('#f6f0ff', '#7a3ad6', 'D'),
          unit_price: 14.99, qty: 1, line_total: 14.99, product_price: 14.99, discounts: [] },
      ],
      timeline: [
        { label: 'Recurring charge captured · PayPal', time: '2026-06-19 06:00' },
        { label: 'Order created from SUB-20452 (cycle 3)', time: '2026-06-19 06:00' },
        { label: 'One-time Vitamin D3 add-on included', time: '2026-06-19 06:00' },
        { label: 'Shipped · USPS', time: '2026-06-20 11:00' },
      ],
    },
    // Mixed initial order — a one-time item + the first cycle of a new subscription (SUB-20460).
    5044: {
      order_id: 5044, order_sn: 'EN1036', status: 'to_ship', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-18 10:30', pay_time: '2026-06-18 10:31',
      source: 'BestCheckout', shopify_writeback_status: 'pending', shopify_order_id: '', shopify_writeback_detail: 'Waiting for Shopify Admin API acceptance. Fulfillment is held until write-back succeeds.',
      payment_method: 'Stripe Card', delivery_name: '', delivery_id: '',
      user: { nickname: 'Mia Anderson', uid: 80460 },
      shipping: { first_name: 'Mia', last_name: 'Anderson', detail: '19 Willow Ct', detail2: '',
        city: 'San Diego', province: 'CA', post_code: '92101', country: 'United States',
        phone_code: '1', phone: '619 555 0177', email: 'mia.a@example.com' },
      note: 'First subscription order — also includes a one-time mug.',
      sub: { id: 'SUB-20460', cycle: 1, next: '2026-06-23', deliveryLabel: 'Delivery every 1 month (-$2.60)' },
      total_num: 2, subtotal: 41.99, shipping_fee: 0.00, total: 41.99, paid_amount: 41.99,
      order_discounts: [], shipping_discounts: [], total_savings: 2.60,
      items: [
        { title: 'Signature Blend Coffee 500g', sku: 'Whole bean', image: IMG('#f3ece1', '#7a5c3a', 'C'),
          unit_price: 26.60, qty: 1, line_total: 26.60, product_price: 24.00, discounts: [{ name: 'Subscription discount', amount: 2.60 }],
          subLine: true },
        { title: 'Ceramic Pour-Over Mug', sku: 'Stone / 12oz', image: IMG('#eef0f4', '#525a6b', 'M'),
          unit_price: 17.99, qty: 1, line_total: 17.99, product_price: 17.99, discounts: [] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-18 10:30' },
        { label: 'Captured by BestCheckout funnel', time: '2026-06-18 10:30' },
        { label: 'Payment captured · Stripe Card', time: '2026-06-18 10:31' },
        { label: 'Shopify write-back pending', time: '2026-06-18 10:31' },
        { label: 'Subscription SUB-20460 started (Signature Blend Coffee)', time: '2026-06-18 10:31' },
      ],
    },
    // Bundle order — the bundle's component SKUs (+ a gift) are grouped under one bundle block.
    5043: {
      order_id: 5043, order_sn: 'EN1035', status: 'shipped', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-17 15:12', pay_time: '2026-06-17 15:13',
      payment_method: 'PayPal', delivery_name: 'FedEx', delivery_id: 'FX882001774521',
      user: { nickname: 'Jordan Park', uid: 80588 },
      shipping: { first_name: 'Jordan', last_name: 'Park', detail: '300 Spear St', detail2: 'Apt 12',
        city: 'San Francisco', province: 'CA', post_code: '94105', country: 'United States',
        phone_code: '1', phone: '415 555 0150', email: 'jordan.park@example.com' },
      note: '',
      bundle: { id: 'BND-01', name: 'Focus Gum — Multipack' },
      total_num: 3, subtotal: 49.30, shipping_fee: 0.00, total: 49.30, paid_amount: 49.30,
      order_discounts: [], shipping_discounts: [], total_savings: 48.70,
      items: [
        { title: 'Neurix Focus & Energy Gum', sku: '2 PCS · 60-piece', image: IMG('#eaf3ff', '#1d4ed8', 'N'), bundleMeta: { bundleDiscount: 'Bundle Discount (-$48.70)' },
          unit_price: 49.00, qty: 2, line_total: 98.00, product_price: 49.30, discounts: [{ name: 'Bundle Discount', amount: 48.70 }],
          bundle: 'Focus Gum — Multipack' },
        { title: 'Focus E-Book', sku: 'Digital download', image: IMG('#f3eaff', '#7a3ad6', 'E'), bundleMeta: { bundleDiscount: 'Bundle Discount (-$48.70)' },
          unit_price: 0, qty: 1, line_total: 0, product_price: 0, discounts: [],
          bundle: 'Focus Gum — Multipack', gift: true },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-17 15:12' },
        { label: 'Payment captured · PayPal', time: '2026-06-17 15:13' },
        { label: 'Shipped · FedEx', time: '2026-06-18 09:30' },
      ],
    },
    5042: {
      order_id: 5042, order_sn: 'EN1033', status: 'to_ship', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-04 14:22', pay_time: '2026-06-04 14:24',
      source: 'BestCheckout', shopify_writeback_status: 'synced', shopify_order_id: '#SHP-89142', shopify_writeback_detail: 'Written back to Shopify and ready for the installed fulfillment app.',
      payment_method: 'Stripe Card',
      delivery_name: '', delivery_id: '',
      user: { nickname: 'Emma Whitfield', uid: 81245 },
      shipping: {
        first_name: 'Emma', last_name: 'Whitfield', detail: '482 Lakeview Drive', detail2: 'Apt 5B',
        city: 'Chicago', province: 'IL', post_code: '60614', country: 'United States',
        phone_code: '1', phone: '312 555 0148', email: 'emma.whitfield@example.com',
      },
      note: 'VIP customer — priority handling. Leave the package at the front desk if no one answers.',
      // amount breakdown (subtotal after product discounts; order + shipping discounts shown separately)
      total_num: 4, subtotal: 191.00, shipping_fee: 12.00, total: 172.60, paid_amount: 172.60,
      order_discounts: [{ name: 'WELCOME10', amount: 18.40 }],
      shipping_discounts: [{ name: 'Free shipping over $150', amount: 12.00 }],
      total_savings: 40.40,
      items: [
        { title: '3D Anti-Cellulite Leggings', sku: 'beige / m', image: IMG('#e6f0ff', '#0058c4', 'L'),
          unit_price: 49.00, qty: 2, line_total: 98.00, product_price: 89.00,
          discounts: [{ name: 'THANKU25', amount: 9.00 }] },
        { title: 'Pocket Sculpting Leggings', sku: 'grey / l', image: IMG('#efe9ff', '#6d28d9', 'P'),
          unit_price: 39.00, qty: 1, line_total: 39.00, product_price: 39.00, discounts: [] },
        { title: 'Compression Sleeves (pair)', sku: 'black / os', image: IMG('#e0f2ec', '#00684a', 'C'),
          unit_price: 64.00, qty: 1, line_total: 64.00, product_price: 63.00,
          discounts: [{ name: 'WELCOME10', amount: 1.00 }] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-04 14:22' },
        { label: 'Captured by BestCheckout funnel', time: '2026-06-04 14:22' },
        { label: 'Payment captured · Stripe Card', time: '2026-06-04 14:24' },
        { label: 'Written back to Shopify · #SHP-89142', time: '2026-06-04 14:24' },
        { label: 'Fulfillment app notified from Shopify', time: '2026-06-04 14:24' },
        { label: 'Buyer notified', time: '2026-06-04 14:24' },
      ],
    },
    5040: {
      order_id: 5040, order_sn: 'EN1031', status: 'shipped', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-03 19:41', pay_time: '2026-06-03 19:43',
      source: 'BestCheckout', shopify_writeback_status: 'failed', shopify_order_id: '', shopify_writeback_detail: 'Shopify rejected the write-back because shipping profile data is stale. Retry after fixing Connection.',
      payment_method: 'PayPal',
      delivery_name: 'FedEx', delivery_id: 'FX774120938455',
      user: { nickname: 'Olivia Martins', uid: 80877 },
      shipping: {
        first_name: 'Olivia', last_name: 'Martins', detail: '226 Peachtree Rd NE', detail2: 'Suite 12',
        city: 'Atlanta', province: 'GA', post_code: '30309', country: 'United States',
        phone_code: '1', phone: '404 555 7781', email: 'olivia.martins@example.com',
      },
      note: '',
      total_num: 5, subtotal: 232.80, shipping_fee: 0.00, total: 232.80, paid_amount: 232.80,
      order_discounts: [],
      shipping_discounts: [],
      total_savings: 12.20,
      items: [
        { title: 'Butt-Lifting Capris', sku: 'black / s', image: IMG('#e6f0ff', '#0058c4', 'B'),
          unit_price: 45.00, qty: 3, line_total: 135.00, product_price: 135.00, discounts: [] },
        { title: 'Seamless Briefs (3-pack)', sku: 'nude / m', image: IMG('#fff4e0', '#9a6400', 'S'),
          unit_price: 55.00, qty: 2, line_total: 110.00, product_price: 97.80,
          discounts: [{ name: 'SUMMER20', amount: 12.20 }] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-03 19:41' },
        { label: 'Captured by BestCheckout funnel', time: '2026-06-03 19:41' },
        { label: 'Payment captured · PayPal', time: '2026-06-03 19:43' },
        { label: 'Shopify write-back failed · shipping profile stale', time: '2026-06-03 19:44' },
        { label: 'Fulfilled · FedEx FX774120938455', time: '2026-06-03 22:10' },
      ],
    },
    5039: {
      order_id: 5039, order_sn: 'EN1030', status: 'review', paid: 1, order_type: 1,
      payment_status: 'paid', verify_code: 'VC-39A7K2',
      create_time: '2026-06-03 08:55', pay_time: '2026-06-03 08:57',
      payment_method: 'Stripe ApplePay',
      delivery_name: '', delivery_id: '',
      user: { nickname: 'Noah Thompson', uid: 80541 },
      shipping: {
        first_name: 'Noah', last_name: 'Thompson', detail: '900 Westheimer Rd', detail2: '',
        city: 'Houston', province: 'TX', post_code: '77006', country: 'United States',
        phone_code: '1', phone: '713 555 2290', email: 'noah.t@example.com',
      },
      note: 'Gift — no invoice in the box please.',
      total_num: 1, subtotal: 64.00, shipping_fee: 0.00, total: 64.00, paid_amount: 64.00,
      order_discounts: [], shipping_discounts: [], total_savings: 0.00,
      items: [
        { title: 'Short Leggings', sku: 'black / m', image: IMG('#e6f0ff', '#0058c4', 'S'),
          unit_price: 64.00, qty: 1, line_total: 64.00, product_price: 64.00, remaining: 1, discounts: [] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-03 08:55' },
        { label: 'Payment captured · Stripe ApplePay', time: '2026-06-03 08:57' },
        { label: 'Verification code issued · VC-39A7K2', time: '2026-06-03 08:57' },
      ],
    },
    5041: {
      order_id: 5041, order_sn: 'EN1032', status: 'to_pay', paid: 0, order_type: 0,
      payment_status: 'unpaid', verify_code: '',
      create_time: '2026-06-04 11:08', pay_time: null,
      payment_method: '--',
      delivery_name: '', delivery_id: '',
      user: { nickname: 'Liam Sørensen', uid: 80910 },
      shipping: {
        first_name: 'Liam', last_name: 'Sørensen', detail: '17 Harbour Street', detail2: '',
        city: 'Sydney', province: 'NSW', post_code: '2000', country: 'Australia',
        phone_code: '61', phone: '2 8123 4567', email: 'liam.sorensen@example.com',
      },
      note: '',
      total_num: 2, subtotal: 96.00, shipping_fee: 0.00, total: 96.00, paid_amount: 0.00,
      order_discounts: [], shipping_discounts: [], total_savings: 0.00,
      items: [
        { title: 'Compression Sleeves (pair)', sku: 'black / os', image: IMG('#e0f2ec', '#00684a', 'C'),
          unit_price: 48.00, qty: 2, line_total: 96.00, product_price: 96.00, discounts: [] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-04 11:08' },
        { label: 'Awaiting payment', time: '2026-06-04 11:08' },
      ],
    },
    5037: {
      order_id: 5037, order_sn: 'EN1028', status: 'refund', paid: 1, order_type: 0,
      payment_status: 'paid', verify_code: '',
      create_time: '2026-06-02 16:30', pay_time: '2026-06-02 16:33',
      payment_method: 'Stripe Card',
      delivery_name: '', delivery_id: '',
      user: { nickname: 'William Hughes', uid: 79980 },
      shipping: {
        first_name: 'William', last_name: 'Hughes', detail: '11 King Street West', detail2: '',
        city: 'Toronto', province: 'ON', post_code: 'M5H 1A1', country: 'Canada',
        phone_code: '1', phone: '416 555 0199', email: 'w.hughes@example.com',
      },
      note: 'Customer reported wrong size — full refund approved.',
      total_num: 1, subtotal: 78.00, shipping_fee: 0.00, total: 78.00, paid_amount: 0.00,
      order_discounts: [], shipping_discounts: [], total_savings: 0.00,
      items: [
        { title: 'Butt-Lifting Capris', sku: 'grey / l', image: IMG('#e6f0ff', '#0058c4', 'B'),
          unit_price: 78.00, qty: 1, line_total: 78.00, product_price: 78.00, discounts: [] },
      ],
      timeline: [
        { label: 'Order placed', time: '2026-06-02 16:30' },
        { label: 'Payment captured · Stripe Card', time: '2026-06-02 16:33' },
        { label: 'Refund of $78.00 issued · Wrong size', time: '2026-06-02 18:12' },
      ],
    },
  };

  window.DATA_ORDERS = {
    TABS, KEYWORD_OPTIONS, TIME_OPTIONS, ORDERS, DETAILS,
    // Refund reasons (getRefundReasons) — referenced in the Refund modal helper text only
    REFUND_REASONS: [
      'Out of stock', 'Customer changed mind', 'Wrong item shipped',
      'Damaged in transit', 'Size / fit issue', 'Duplicate order', 'Other',
    ],
  };
})();
